[build]
  command = "npx eleventy"
  publish = "_site"
[build.environment]
  NODE_ENV = "16.15.0"
[build.processing]
  skip_processing = false
[build.processing.css]
  minify = true
[build.processing.images]
  compress = true
